fix: add OrderStatusURL to the struct
MOHC-LTD/shopify pull request #144
Opened 2024-09-03 13:45 UTC by RohanLeach

2024-09-03 13:54 UTC, JamesFowke commented on orders.go
> +	// orderStatusURL to find the order status
```suggestion
	// OrderStatusURL to find the order status
```

2024-09-05 10:24 UTC, nichharp-mohc commented on orders.go
> +	// OrderStatusURL to find the order status
```suggestion
	// OrderStatusURL is the Thank You page (Shopify doubles it as a order status page)
```
Note that there's 2 URLs for this sorta thing. There's a legit thank you page with `thank_you` in the URL and then this one.
The user is only shown the thank you page once, when it's attempted to be hit again the user is redirected to the OrderStatusURL.
This is why tracking on this page might get complicated. We need that spike I mentioned before on how we can track this.

2024-09-06 11:23 UTC, nichharp-mohc requested changes

2024-09-06 11:23 UTC, nichharp-mohc commented on orders.go
> +	CreateSkipCheckout(order Order) (Order, error)
```suggestion
	// Create creates a new fulfilled order
	CreateFulfilled(order Order) (Order, error)
```

2024-09-06 11:23 UTC, nichharp-mohc commented on orders.go
> +	// OrderStatusURL is the Thank You page (Shopify doubles it as a order status page)
```suggestion
	// OrderStatusURL the URL pointing to the order status web page, if applicable.
```

2024-09-09 10:18 UTC, ezelopes-mohc approved these changes

2024-09-13 12:58 UTC, nichharp-mohc approved these changes

2024-09-24 12:03 UTC, merged